site_name: PARSEC Labs
theme: readthedocs

pages:
  - Home: index.md
  - 'JSON RPC':
    - Overview: JSON-RPC/overview.md
    - 'web3.eth': JSON-RPC/web3.eth.md
    - 'web3.net': JSON-RPC/web3.net.md
    - 'web3.parsec': JSON-RPC/web3.parsec.md
