site_name: PARSEC Labs
theme: readthedocs

nav:
    - Home: index.md
    - JSON RPC:
        - web3.eth: json-rpc/web3.eth.md
        - web3.net: json-rpc/web3.net.md
        - web3.parsec: json-rpc/web3.parsec.md
